apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: default
  labels:
    app: gitops-demo-app
    managed-by: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: gitops-demo-app
        image: premkumar71/gitops-demo-app:v2
        imagePullPolicy: Always
        env:
        - name: APP_VERSION
          value: "1.0"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
